---
title: "labnoteforLavaan"
output: pdf_document
date: "2023-12-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading graph from Tetrad and come out with the graph without standlized

```{r}
library(lavaan)
setwd('/Users/jonah/Downloads/lab_data/')
# load graph file (txt) saved from Tetrad
con = file('12_19_graph.txt', "r")
while ( TRUE ) {
  line = readLines(con, n = 1)
  if ( length(line) == 0|line=='Graph Edges:' ) {
    break
  }
}
el<-data.frame()
while ( TRUE ) {
  line = readLines(con, n = 1)
  if ( line == "" ) {
    break
  }
  el<-rbind(el,t(as.data.frame(strsplit(line,split=' ')[[1]][2:4])))
}

close(con)
rownames(el) <- NULL
names(el)<-c('source','edgetype','target')

# now make model string for lavaan
mdstr<-''
for (i in 1:nrow(el)){
  e<-el[i,, drop=FALSE]
  if (e$edgetype=='-->'){
    # estimating o-> as  as '-->' here
    mdstr<-paste0(mdstr,e$target,'~',e$source,'\n')
  }
  if(e$edgetype=='<->'|e$edgetype=='o-o'|e$edgetype=='o->'){ 
    
    mdstr<-paste0(mdstr,e$source,'~~',e$target,'\n')
  }
}

# fit lavaan model
library(lavaan)
data<-read.table("Jonah_Y0_Y1_Model_3.csv1_final_copy.txt",header= TRUE)
fit<-sem(mdstr,data=data)

summary(fit,fit.measures=TRUE)
```

## Loading graph from Causal-Cmd and come out with the graph without standlized

```{r}
library(lavaan)
setwd('/Users/jonah/Downloads/lab_data/')
# load graph file (txt) saved from Tetrad
con = file('graspfci_1701977640763_out.txt', "r")
while ( TRUE ) {
  line = readLines(con, n = 1)
  if ( length(line) == 0|line=='Graph Edges:' ) {
    break
  }
}
el<-data.frame()
while ( TRUE ) {
  line = readLines(con, n = 1)
  if ( line == "" ) {
    break
  }
  el<-rbind(el,t(as.data.frame(strsplit(line,split=' ')[[1]][2:4])))
}

close(con)
rownames(el) <- NULL
names(el)<-c('source','edgetype','target')

# now make model string for lavaan
mdstr<-''
for (i in 1:nrow(el)){
  e<-el[i,, drop=FALSE]
  if (e$edgetype=='-->'){
    # estimating o-> as  as '-->' here
    mdstr<-paste0(mdstr,e$target,'~',e$source,'\n')
  }
  if(e$edgetype=='<->'|e$edgetype=='o-o'|e$edgetype=='o->'){ 
    
    mdstr<-paste0(mdstr,e$source,'~~',e$target,'\n')
  }
}

# fit lavaan model
library(lavaan)
data<-read.table("Jonah_Y0_Y1_Model_3.csv1_final_copy.txt",header= TRUE)
fit<-sem(mdstr,data=data)
summary(fit,fit.measures=TRUE)
```

## Loading graph from Tetrad and come out with the graph with standlized

```{r}
library(lavaan)
setwd('/Users/jonah/Downloads/lab_data/')
# load graph file (txt) saved from Tetrad
con = file('12_19_graph.txt', "r")
while ( TRUE ) {
  line = readLines(con, n = 1)
  if ( length(line) == 0|line=='Graph Edges:' ) {
    break
  }
}
el<-data.frame()
while ( TRUE ) {
  line = readLines(con, n = 1)
  if ( line == "" ) {
    break
  }
  el<-rbind(el,t(as.data.frame(strsplit(line,split=' ')[[1]][2:4])))
}

close(con)
rownames(el) <- NULL
names(el)<-c('source','edgetype','target')

# now make model string for lavaan
mdstr<-''
for (i in 1:nrow(el)){
  e<-el[i,, drop=FALSE]
  if (e$edgetype=='-->'){
    # estimating o-> as  as '-->' here
    mdstr<-paste0(mdstr,e$target,'~',e$source,'\n')
  }
  if(e$edgetype=='<->'|e$edgetype=='o-o'|e$edgetype=='o->'){ 
    
    mdstr<-paste0(mdstr,e$source,'~~',e$target,'\n')
  }
}

# fit lavaan model
library(lavaan)
data<-read.table("Jonah_Y0_Y1_Model_3.csv1_final_copy.txt",header= TRUE)
fit<-sem(mdstr,data=scale(data))

summary(fit,fit.measures=TRUE)
```

```{r}
sink(file = "mean.txt")
newdata <- subset(data, data$Y0_CD >=0.5 )
means <- colMeans(newdata)
means
sink(file = NULL)
```


