---
title: "lab"
output: html_document
date: "2024-01-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lavaan)
setwd('/Users/jonah/Downloads/lab_data/')
# load graph file (txt) saved from Tetrad
con = file('12_19_graph.txt', "r")
while ( TRUE ) {
  line = readLines(con, n = 1)
  if ( length(line) == 0|line=='Graph Edges:' ) {
    break
  }
}
el<-data.frame()
while ( TRUE ) {
  line = readLines(con, n = 1)
  if ( line == "" ) {
    break
  }
  el<-rbind(el,t(as.data.frame(strsplit(line,split=' ')[[1]][2:4])))
}

close(con)
rownames(el) <- NULL
names(el)<-c('source','edgetype','target')

# now make model string for lavaan
mdstr<-''
for (i in 1:nrow(el)){
  e<-el[i,, drop=FALSE]
  if (e$edgetype=='-->'){
    # estimating o-> as  as '-->' here
    mdstr<-paste0(mdstr,e$target,'~',e$source,'\n')
  }
  if(e$edgetype=='<->'|e$edgetype=='o-o'|e$edgetype=='o->'){ 
    
    mdstr<-paste0(mdstr,e$source,'~~',e$target,'\n')
  }
}

# fit lavaan model
library(lavaan)
data<-read.table("Jonah_Y0_Y1_Model_3.csv1_final_copy.txt",header= TRUE)
fit<-sem(mdstr,data=data)
fit
summary(fit,fit.measures=TRUE)
#data2
#install.packages("xlsx")

```

```{r}

# different method
# 1.
data2 = data
data2$Y0_CD = data$Y0_CD*0.25
data2$Y0_CD
data$Y0_CD

fit3<-sem(mdstr,data=data2)
fit3
summary(fit3,fit.measures=TRUE)

# modify the data with 50 percent less with Y0_ARREST
data2 = data

num_ones_to_change <- sum(data2$Y0_CD == 1) * 0.5
one_indices <- which(data2$Y0_ARREST == 1)
indices_to_change <- sample(one_indices, num_ones_to_change)
data2$Y0_ARREST[indices_to_change] <- 0

data2
fit2<-sem(mdstr,data=data2)
vartable(fit2)
```

```{r}
data$Y0_CD
result <- sum(data$Y0_CD[data$Y0_CD >= 0.5])
length(data$Y0_CD[data$Y0_CD >= 0.5])
sum(data$Y0_CD)
length(data$Y0_CD)
result
```

```{r}
#Select the data for Y0_CD>=1
newdata <- subset(data, data$Y0_CD >=0.5 )
newdata
fit3<-sem(mdstr,data=newdata)
summary(fit3,fit.measures=TRUE)
```

```{r}
#Select the data for Y0_ARREST=1
newdata2 <- subset(data, data$Y0_ARREST==1,header = True)
data
newdata2 = subset(newdata2, select = -Y0_ARREST)
fit4<-sem(mdstr,data=newdata2)
summary(fit4,fit.measures=TRUE)
which(is.na(newdata2))
```
